// ─────────────────────────────────────────────────────────────────────────────
// Virilocity V16.4 — Terms of Service (AppSource required)
// V14.3 pricing · Reddit human-approval clause · NJ governing law
// ─────────────────────────────────────────────────────────────────────────────
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Virilocity terms of service — subscription, acceptable use, and limitations.',
};

export default function TermsPage() {
  return (
    <main id="main-content" className="max-w-3xl mx-auto px-6 py-16">
      <h1 className="text-3xl font-bold text-navy mb-2">Terms of Service</h1>
      <p className="text-slate-400 text-sm mb-8">Effective: April 2026 · Version 16.4</p>

      {[
        {
          title: '1. Subscription & Pricing',
          body: 'Virilocity V14.3 pricing: Free ($0), Starter ($79/month), Pro ($399/month), Growth ($699/month), Scale ($999/month), Enterprise (custom). Annual subscriptions offer approximately 20% discount. All prices in USD. CloudOneSoftware LLC reserves the right to change pricing with 30 days notice.',
        },
        {
          title: '2. B2B Seat Licensing',
          body: 'B2B organization plans include: Pro (5 seats), Growth (20 seats), Scale (100 seats), Enterprise (unlimited). Seats are assigned via the organization dashboard. Exceeding seat limits requires upgrade. SAML 2.0 SSO is available on Enterprise tier only.',
        },
        {
          title: '3. Acceptable Use',
          body: 'You may use Virilocity for lawful marketing automation. You may not use the platform to generate spam, misleading content, or content that violates applicable laws. Our AI content fairness filter actively prevents generation of demographic-targeting or discriminatory content.',
        },
        {
          title: '4. Social Media Automation — Reddit Policy',
          body: 'The Virilocity platform never autonomously posts to Reddit. The Reddit Manager agent discovers relevant threads and drafts responses, but all Reddit actions require explicit human approval through the platform interface. This restriction is hardcoded and cannot be disabled at any subscription tier.',
        },
        {
          title: '5. Microsoft 365 & Graph API',
          body: 'Use of Microsoft 365 integration features requires a valid Microsoft 365 account and compliance with Microsoft\'s terms of service. Graph API permissions requested are disclosed in our Privacy Policy and the AppSource compliance endpoint (/appsource/compliance).',
        },
        {
          title: '6. AI-Generated Content',
          body: 'Content generated by Virilocity AI agents is suggestions for human review. You are responsible for reviewing and approving AI-generated content before publication. The platform\'s fairness filter reduces bias in content, but does not guarantee compliance with all regulatory requirements.',
        },
        {
          title: '7. Data & Intellectual Property',
          body: 'You retain ownership of your data. You grant CloudOneSoftware LLC a limited license to process your data to provide the service. AI model outputs are not owned by Anthropic or CloudOneSoftware LLC per Anthropic\'s usage policies.',
        },
        {
          title: '8. Limitation of Liability',
          body: 'CloudOneSoftware LLC\'s liability is limited to the amount paid in the 3 months preceding any claim. We are not liable for indirect, incidental, or consequential damages.',
        },
        {
          title: '9. Governing Law',
          body: 'These terms are governed by the laws of the State of New Jersey, United States. Disputes shall be resolved in Hudson County, New Jersey.',
        },
        {
          title: '10. Contact',
          body: 'CloudOneSoftware LLC · Jersey City, NJ · legal@virilocity.io',
        },
      ].map(({ title, body }) => (
        <section key={title} aria-labelledby={title.replace(/\s+/g, '-').toLowerCase()} className="mb-8">
          <h2 id={title.replace(/\s+/g, '-').toLowerCase()} className="text-xl font-bold text-navy mb-2">{title}</h2>
          <p className="text-slate-600 leading-relaxed">{body}</p>
        </section>
      ))}
    </main>
  );
}
